/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb --transform 
Files: optimized-room.glb [825.36KB] > D:\Projects\portfolio\portfolio\public\models\optimized-room-transformed.glb [78.95KB] (90%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Room(props) {
  const { nodes, materials } = useGLTF(
    "/models/optimized-room-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes._________6_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.emis_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        geometry={nodes.window4_phong1_0.geometry}
        material={materials.phong1}
      />
    </group>
  );
}

useGLTF.preload("/optimized-room-transformed.glb");
